import React, { useState } from 'react';
import Head from 'next/head';

import Header from '@/components/Header';
import Slider from '@/components/Slider';
import Calculator from '@/components/Calculator';

export default function HomePage() {

  const [openPopup, setOpenPopup] = useState<boolean>(false);

  return (
    <>
      <Head>
        <title>OXEM</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header openPopup={openPopup} setOpenPopup={setOpenPopup}/>
      <main>
        <Slider setOpenPopup={setOpenPopup}/>
        <Calculator setOpenPopup={setOpenPopup}/>
      </main>
    </>
  )
}
